export enum DonationStatus {
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RECEIVED = 'RECEIVED',
  ALLOCATED = 'ALLOCATED',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
}
